### ISSUE TITLE
Project name conflict

### ISSUE THREAD

**Issue by mdesalvo** [giacomociti/iride#1]
Hi, is this project somewhat related to the real [RDFSharp](https://github.com/mdesalvo/RDFSharp)?
If not related, and if neither a fork or a derivate work, there should not exist two projects with same name in same development area (.NET, RDF) because this would really mislead developers. 
Can you please kindly rename the project? 
Thanks in advance.

**Comment by giacomociti** [comment]
Sorry, I wasn't aware of the name conflict. I'll rename this project

**Comment by giacomociti** [comment]
Renamed to iride, an Italian word whose letters remind of IRI and IDE, since this project is just a generator of static Uri properties to help accessing IRIs in ontologies from an IDE.
